#!/bin/bash

# shellcheck disable=SC2139

# aliasrc
# aliases for bash

# better not to have too many aliases so as not to get confused in the scripts

# doas
alias d="doas"
# space after alias make bash try to interpret also next word as alias
# some problems with aliases that use doas not at the start of the alias
# alias doas="doas "
# alias d="doas "

# do not keep environment variables when su
alias sul="su --login --whitelist-environment=SSH_TTY,WAYLAND_DISPLAY"

# change directory
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."
alias .1="cd .."
alias .2="cd ../.."
alias .3="cd ../../.."
alias .4="cd ../../../.."
alias cd..="cd .."
alias cd...="cd ../.."
alias cd....="cd ../../.."
alias cd.....="cd ../../../.."
alias cd1="cd .."
alias cd2="cd ../.."
alias cd3="cd ../../.."
alias cd4="cd ../../../.."

# ls
alias ls='$LS_COMMAND'
alias la='$LS_COMMAND -A'
alias ll='$LS_COMMAND -l'
alias lal='$LS_COMMAND -A -l'
alias lla='$LS_COMMAND -l -A'
# alias trexa="exa --long --header --modified --git --tree --color=auto --icons --all --group-directories-first"

# color stuff
if [ ! "$OPERATING_SYSTEM" = "openbsd" ]; then
    alias diff="diff --color=auto"
else
    alias diff="colordiff"
fi
# alias dir="dir --color=auto"
# alias vdir="vdir --color=auto"
# alias ip="ip --color=auto"
# alias grep="grep --color=auto"

# ignore case
# alias grepi="grep --color=auto -i"
# alias rgi="rg -i"

# hidden
# alias fdh="fd --hidden"
# alias rgh="rg --hidden"

# verbose and recursive
# alias mkdir="mkdir -pv"
# alias cp="cp -r"
# alias mv="mv -f -v"
# alias rm='echo "in order to move the file/directory in the trash use trash-put"; rm'
# alias rmr="rm -r"

# space on disk
# alias space="du -sh"
# alias space-sub="du -h -d 1"

# human-readable sizes
# alias df='df -h'
# show sizes in MB
# alias free='free -m'

# ps (current processes)
# alias psa="ps auxf"
# alias psgrep="ps aux | grep -v grep | grep -i -e VSZ -e"
# alias psmem='ps auxf | sort -nr -k 4'
# alias pscpu='ps auxf | sort -nr -k 3'

# if [ "$OS_TYPE" = "desktop" ]; then
    # wayland
    # alias imv="imv-wayland"
    # alias firefox="firefox-wayland"
# fi

# kak
alias ka="kak"
# alias kak="kak-smart no"
# alias ka="kak-smart no"
alias kakf="kak-fzf-bash no"
alias kaf="kak-fzf-bash no"

alias nv="nvim"

alias n3="nnn"
alias n3p="nnn-pre"

alias zathura="zat"

if [ "$OPERATING_SYSTEM" = "void" ]; then
    alias xq="xbps-query"
fi

# verify signature
alias gpg-verify="gpg --keyserver-options auto-key-retrieve --verify"
# receive signature
alias gpg-receive="gpg --keyserver-options auto-key-retrieve --receive-keys"

# yt-dl
alias ydl='$YTDL'
alias ydlv='$YTDL --ignore-errors --retries=infinite'
alias ydlvm='$YTDL --ignore-errors --retries=infinite --add-metadata --xattrs'
alias ydla='$YTDL --ignore-errors --retries=infinite --extract-audio'
alias ydlam='$YTDL --ignore-errors --retries=infinite --extract-audio --add-metadata --xattrs'

# fzf with preview
alias fzfp='fzf --preview="$FZF_DEFAULT_PREVIEW"'

# zigup
alias zigup='zigup --install-dir "${XDG_LIB_HOME:-$HOME/.local/lib}/zigup"'

# rust global
alias rust-set-global='source /usr/local/bin/rust-set-global'
# rust local
alias rust-set-local='source /usr/local/bin/rust-set-local'

# wifi
alias iwscan="iwctl station wlan0 scan;"

# bluetooth
alias bluescan="bluetoothctl scan on;"
alias bluectl="echo \"scan on\"; echo \"trust\"; echo \"connect\"; bluetoothctl"

# lists the installed system libraries
alias listlib="scanelf --ldpath -BF '%f'"

# weather
# https://github.com/chubin/wttr.in
export weather="wttr.in"
# curl wttr.in/:help

if [ "$OS_TYPE" = "desktop" ]; then
    # river
    export gui="Mod4"
    export alt="Mod1"

    # newsboat
    alias nb='newsboat'
    alias nbp='newsboat \
        -u "${XDG_CONFIG_HOME:-$HOME/.config}/newsboat/urls-podcast" \
        -c "${XDG_DATA_HOME:-$HOME/.local/share}/newsboat/cache-podcast.db"'
    alias nbs='newsboat \
        -u "${XDG_CONFIG_HOME:-$HOME/.config}/newsboat/urls-social" \
        -c "${XDG_DATA_HOME:-$HOME/.local/share}/newsboat/cache-social.db"'
    alias nbv='newsboat \
        -u "${XDG_CONFIG_HOME:-$HOME/.config}/newsboat/urls-video" \
        -c "${XDG_DATA_HOME:-$HOME/.local/share}/newsboat/cache-video.db"'
    alias nbvn='newsboat \
        -u "${XDG_CONFIG_HOME:-$HOME/.config}/newsboat/urls-video-no-youtube" \
        -c "${XDG_DATA_HOME:-$HOME/.local/share}/newsboat/cache-video-no-youtube.db"'
    alias nby='newsboat \
        -u "${XDG_CONFIG_HOME:-$HOME/.config}/newsboat/urls-youtube" \
        -c "${XDG_DATA_HOME:-$HOME/.local/share}/newsboat/cache-youtube.db"'
    alias nbyn='newsboat \
        -u "${XDG_CONFIG_HOME:-$HOME/.config}/newsboat/urls-youtube-no-odysee" \
        -c "${XDG_DATA_HOME:-$HOME/.local/share}/newsboat/cache-youtube-no-odysee.db"'
fi

# git related
alias gst="git status"
alias gad="git add"
alias grs="git restore"
alias gbr="git branch"
alias gcm="git commit"
alias gdf="git diff"
alias gfe="git fetch"
alias glg="git log"
alias gco="git checkout"
alias gpl="git pull"
alias gps="git push"
alias grb="git rebase"
alias gsa="git stash"

if [ "$OS_TYPE" = "desktop" ]; then
    # ucon
    alias ust="ucon status"
    alias uad="ucon add"
    alias urs="ucon restore"
    alias ucm="ucon commit"
    alias udf="ucon diff"
    alias ulg="ucon log"
    alias upl="ucon pull"
    alias ups="ucon push"

    # pcon
    alias pst="pcon status"
    alias pad="pcon add"
    alias prs="pcon restore"
    alias pcm="pcon commit"
    alias pdf="pcon diff"
    alias plg="pcon log"
    alias ppl="pcon pull"
    alias pps="pcon push"

    # rcon
    alias rst="rcon status"
    alias rad="rcon add"
    alias rrs="rcon restore"
    alias rcm="rcon commit"
    alias rdf="rcon diff"
    alias rlg="rcon log"
    alias rpl="rcon pull"
    alias rps="rcon push"
else
    # ucon
    dotfiles_dir="$HOME/dotfiles"
    alias ust="git -C $dotfiles_dir status"
    alias uad="git -C $dotfiles_dir add"
    alias urs="git -C $dotfiles_dir restore"
    alias ucm="git -C $dotfiles_dir commit"
    alias udf="git -C $dotfiles_dir diff"
    alias ulg="git -C $dotfiles_dir log"
    alias upl="git -C $dotfiles_dir pull"
    alias ups="git -C $dotfiles_dir push"
    unset dotfiles_dir
    # pcon
    private_dir="$HOME/private"
    alias pst="git -C $private_dir status"
    alias pad="git -C $private_dir add"
    alias prs="git -C $private_dir restore"
    alias pcm="git -C $private_dir commit"
    alias pdf="git -C $private_dir diff"
    alias plg="git -C $private_dir log"
    alias ppl="git -C $private_dir pull"
    alias pps="git -C $private_dir push"
    unset private_dir
    # rcon
    config_dir="$HOME/config"
    alias rst="git -C $config_dir status"
    alias rad="git -C $config_dir add"
    alias rrs="git -C $config_dir restore"
    alias rcm="git -C $config_dir commit"
    alias rdf="git -C $config_dir diff"
    alias rlg="git -C $config_dir log"
    alias rpl="git -C $config_dir pull"
    alias rps="git -C $config_dir push"
    unset config
fi
if [ "$OPERATING_SYSTEM" = "void" ]; then
    # void mirrors in order to quickly change when one is slow (-R flag)
    # https://docs.voidlinux.org/xbps/repositories/mirrors/index.html#mirrors
    export mirror1="https://alpha.de.repo.voidlinux.org/current"
    export mirror2="https://repo-fi.voidlinux.org/current"
    export mirror3="https://mirrors.servercentral.com/voidlinux/current"
    export mirror4="https://repo-us.voidlinux.org/current"
fi

# so the root user can link and use bash config
# remember to add package to /etc/config/xbps-packages
if [ "$LOGNAME" = "root" ] || [ "$(id -u)" -eq 0 ]; then
    if [ "$OPERATING_SYSTEM" = "void" ]; then
        alias xi="xbps-install"
        alias xr="xbps-remove"

        alias blueon="sv up bluetoothd; bluetoothctl power on;"
        alias blueoff="bluetoothctl power off; sv down bluetoothd;"

        # alias servstat="sv status /var/service/*"
    fi
else
    if [ "$OPERATING_SYSTEM" = "void" ]; then
        alias xbps-install="doas xbps-install"
        alias xbps-remove="doas xbps-remove"
        alias xi="doas xbps-install"
        alias xr="doas xbps-remove"

        alias blueon="doas sv up bluetoothd; bluetoothctl power on;"
        alias blueoff="bluetoothctl power off; doas sv down bluetoothd;"

        # alias servstat="doas sv status /var/service/*"

        alias poweroff="doas poweroff"
        alias reboot="doas reboot"

        alias zzz="doas zzz"
        alias ZZZ="doas ZZZ"
    elif [ "$OPERATING_SYSTEM" = "debian" ]; then
        alias apt-get="sudo apt-get"

        alias systemctl="sudo systemctl"
    fi

    alias powertop="doas powertop"

    # kak
    alias dkak="doas kak"
    alias dka="doas kak"
    # alias dkak="kak-smart yes"
    # alias dka="kak-smart yes"
    alias dkakf="kak-fzf-bash yes"
    alias dkaf="kak-fzf-bash yes"

    alias dnv="doas nvim"

    alias dn3="doas nnn"
    alias dn3p="doas nnn-pre"
fi
