#!/bin/bash

# aliasrc
# aliases for bash/zsh

# better not to have too many aliases so it is easier when writing scripts

# doas
alias d="doas"
# space after alias make bash try to interpret also next word as alias
# some problems with aliases that use doas not at the start of the alias
# alias doas="doas "
# alias d="doas "

# do not keep environment variables when su
alias su="su --login --whitelist-environment=WAYLAND_DISPLAY"

# change directory
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."
alias cd..="cd .."
alias cd...="cd ../.."
alias cd....="cd ../../.."
alias cd.....="cd ../../../.."

# ls
lsplus="ls --color=auto --group-directories-first --format=horizontal --human-readable"
alias ls='$lsplus'
alias la='$lsplus -a'
alias ll='$lsplus -l'
alias lal='$lsplus -a -l'
alias lla='$lsplus -l -a'
cdl () {
    cd "$@" || return
    $lsplus
}
# alias trexa="exa --long --header --modified --git --tree --color=auto --icons --all --group-directories-first"

# color stuff
alias dir="dir --color=auto"
alias vdir="vdir --color=auto"
alias diff="diff --color=auto"
alias ip="ip --color=auto"
alias grep="grep --color=auto"

# ignore case
# alias grepi="grep --color=auto -i"
# alias rgi="rg -i"

# hidden
# alias fdh="fd --hidden"
# alias rgh="rg --hidden"

# verbose and recursive
# alias mkdir="mkdir -pv"
# alias cp="cp -r"
# alias mv="mv -f -v"
# alias rm='echo "in order to move the file/directory in the trash use trash-put"; rm'
# alias rmr="rm -r"

# space on disk
# alias space="du -sh"
# alias space-sub="du -h -d 1"

# human-readable sizes
# alias df='df -h'
# show sizes in MB
# alias free='free -m'

# ps (current processes)
# alias psa="ps auxf"
# alias psgrep="ps aux | grep -v grep | grep -i -e VSZ -e"
# alias psmem='ps auxf | sort -nr -k 4'
# alias pscpu='ps auxf | sort -nr -k 3'

# replace tabs with 4 spaces
alias tab-rep="sed -i 's/\t/    /g'"

# verify signature
alias gpg-check="gpg --keyserver-options auto-key-retrieve --verify"
# receive signature
alias gpg-retrieve="gpg --keyserver-options auto-key-retrieve --receive-keys"

# programs
alias n3="nnn"
alias n3p="nnn-pre"
alias nv="nvim"
alias kak="kak-smart no"
alias ka="kak-smart no"
alias xq="xbps-query"

# wayland
alias imv="imv-wayland"
alias firefox="firefox-wayland"

# youtube-dl
alias ydlv="youtube-dl --ignore-errors --retries=infinite"
alias ydla="youtube-dl --ignore-errors --retries=infinite --extract-audio"
alias ydlvm="youtube-dl --ignore-errors --retries=infinite --add-metadata --xattrs"
alias ydlam="youtube-dl --ignore-errors --retries=infinite --extract-audio --add-metadata --xattrs"

# fzf with preview
alias fzfp="fzf --preview=\"$FZF_DEFAULT_PREVIEW\""

# wifi
alias iwscan="iwctl station wlan0 scan;"

# bluetooth
alias bluescan="bluetoothctl scan on;"
alias bluectl="echo \"scan on\"; echo \"trust\"; echo \"connect\"; bluetoothctl"

# lists the installed system libraries
alias listlib="scanelf --ldpath -BF '%f'"

# weather
# https://github.com/chubin/wttr.in
export weather="wttr.in"
# curl wttr.in/:help

# zigup
alias zigup="zigup --install-dir \"$XDG_LIB_HOME/zigup\""

# git related
alias gst="git status"
alias gad="git add"
alias gbr="git branch"
alias gcm="git commit"
alias gdf="git diff"
alias gfe="git fetch"
alias glg="git log"
alias gco="git checkout"
alias gps="git push"
alias grb="git rebase"
alias gsa="git stash"
alias gpl="git pull"

# git config
alias ucs="ucon status"
alias uca="ucon add"
alias ucm="ucon commit"
alias ucd="ucon diff"
alias ucp="ucon push"
alias rcs="rcon status"
alias rca="rcon add"
alias rcm="rcon commit"
alias rcd="ucon diff"
alias rcp="rcon push"

# void mirrors in order to quickly change when one is slow (-R flag)
# https://docs.voidlinux.org/xbps/repositories/mirrors/index.html#mirrors
export mirror1="https://alpha.de.repo.voidlinux.org/current"
export mirror2="https://repo-fi.voidlinux.org/current"
export mirror3="https://mirrors.servercentral.com/voidlinux/current"
export mirror4="https://repo-us.voidlinux.org/current"

# so the root user can link and use bash/zsh config
# remember to add package to /etc/config/xbps-packages
if [ "$LOGNAME" = "root" ] || [ "$(id -u)" -eq 0 ]; then
    alias xi="xbps-install"
    alias xr="xbps-remove"

    alias blueon="sv up bluetoothd; bluetoothctl power on;"
    alias blueoff="bluetoothctl power off; sv down bluetoothd;"

    # alias servstat="sv status /var/service/*"

    alias dka="kak-smart no"
else
    alias xbps-install="doas xbps-install"
    alias xbps-remove="doas xbps-remove"
    alias xi="doas xbps-install"
    alias xr="doas xbps-remove"

    alias blueon="doas sv up bluetoothd; bluetoothctl power on;"
    alias blueoff="bluetoothctl power off; doas sv down bluetoothd;"

    # alias servstat="doas sv status /var/service/*"

    alias poweroff="doas poweroff"
    alias reboot="doas reboot"

    alias zzz="doas zzz"
    alias ZZZ="doas ZZZ"

    alias powertop="doas powertop"

    alias dn3="doas nnn"
    alias dn3p="doas nnn-pre"
    alias dnv="doas nvim"
    alias dkak="kak-smart yes"
    alias dka="kak-smart yes"
fi
