#!/bin/bash

# shellcheck disable=SC2207

### completionrc

# alias config='/usr/bin/git --git-dir="$HOME"/.dotfiles/ --work-tree="$HOME"'

# autocomplete alias config (git bare repository)
# remember to sometimes check https://github.com/cykerway/complete-alias
# complete -F _complete_alias config

# in order to find how a command is completed run
# complete -p cmd

## autocomplete doas as sudo

# has to be loaded here or in /etc/bash/bashrc.d/bash_completion.sh
_completion_loader sudo

complete -F _sudo doas
complete -F _sudo d

## autocomplete config as git

# has to be loaded here or in /etc/bash/bashrc.d/bash_completion.sh
_completion_loader git

if [ "$OS_TYPE" = "desktop" ]; then
    complete -o bashdefault -o default -o nospace -F __git_wrap__git_main ucon
    complete -o bashdefault -o default -o nospace -F __git_wrap__git_main pcon
    complete -o bashdefault -o default -o nospace -F __git_wrap__git_main rcon
else
    complete -o bashdefault -o default -o nospace -F __git_wrap__git_main git
fi
if [ "$OPERATING_SYSTEM" = "void" ]; then
    # autocomplete xbps
    complete -F _complete_alias xi
    complete -F _complete_alias xr
    complete -F _complete_alias xq
fi

home_script="${XDG_LOCAL_HOME:-$HOME/.local}/etc/script"

__phel_completion() {
    subject_names="$(sed 's/\n/ /g' "$home_script/phelrc")"

    OPTS="\
        $subject_names \
        -a --all \
        -l --list \
        -h --help \
    "

    COMPREPLY=($(compgen -W "${OPTS}" -- "${COMP_WORDS[$COMP_CWORD]}"))
}
complete -F __phel_completion phel

__build_packages_completion() {
    package_names="$(sed 's/\n/ /g' "$home_script/build-packages")"

    OPTS="\
        $package_names \
        -d --dependencies \
        -n --no-dependencies \
        -l --list-packages \
        -h --help \
    "

    COMPREPLY=($(compgen -W "${OPTS}" -- "${COMP_WORDS[$COMP_CWORD]}"))
}
complete -F __build_packages_completion build-packages

__update_extra_completion() {
    program_names="$(sed 's/\n/ /g' "$home_script/update-extra")"

    OPTS="\
        $program_names \
        -d --dependencies \
        -n --no-dependencies \
        -l --list-programs \
        -h --help \
    "

    COMPREPLY=($(compgen -W "${OPTS}" -- "${COMP_WORDS[$COMP_CWORD]}"))
}
complete -F __update_extra_completion update-extra
