#!/bin/bash
# envrc

export PAGER=less

#export XDG_DOCUMENTS_DIR="${HOME}/documents"
#export XDG_DOWNLOAD_DIR="${HOME}/downloads"
export XDG_CONFIG_HOME="${HOME}/.config"
export XDG_CACHE_HOME="${HOME}/.cache"
export XDG_DATA_HOME="${HOME}/.local/share"
export XDG_STATE_HOME="${HOME}/.local/state"
#export XDG_RUNTIME_DIR="/run/user/$(id -u)"
export XDG_RUNTIME_DIR="${HOME}/.local/runtime"
export ZDOTDIR="${XDG_CONFIG_HOME}/shell"
export GPG_TTY=$(tty)
export GNUPGHOME="${XDG_CONFIG_HOME}/gnupg"
export GTK2_RC_FILES="${XDG_CONFIG_HOME}/gtk-2.0/config"
export C_INCLUDE_PATH="${HOME}/.local/include"
export LD_LIBRARY_PATH="${HOME}/.local/lib"
export PKG_CONFIG_PATH="${HOME}/.local/lib/pkgconfig"

export MANPATH="/usr/share/man:${HOME}/.local/share/man"
export PATH="${PATH}:${HOME}/.local/bin:${HOME}/.cargo/bin"

export LESS='-F -g -i -R -w'
export LESSHISTFILE='$XDG_DATA_HOME/less/lesshst'

# [ Runit ]
# export SVDIR="$XDG_CONFIG_HOME"/service

# NNN
export NNN_OPTS='eEHr'
export NNN_COLORS='3415'
export NNN_FCOLORS='070704030f05060808010301'
export NNN_TRASH=1
export NNN_ARCHIVE="\\.(7z|a|ace|alz|arc|arj|bz|bz2|cab|cpio|deb|gz|jar|lha|lz|lzh|lzma|lzo|rar|rpm|rz|t7z|tar|tbz|tbz2|tgz|tlz|txz|tZ|tzo|war|xpi|xz|Z|zip)$"
export NNN_SEL='/tmp/.sel'
export NNN_FIFO='/tmp/nnn.fifo'

NNN_BMS_CONFIG='c:~/.config;l:~/.local'
NNN_BMS_DEV='v:~/dev'
NNN_BMS_DOC='d:~/doc'
NNN_BMS_DOW='w:~/dow'
export NNN_BMS="$NNN_BMS_CONFIG;$NNN_BMS_DEV;$NNN_BMS_DOC;$NNN_BMS_DOW"



# set wayland environment variables and start river
if [ "$(id -u)" -ne 0 ] && [ -z "${WAYLAND_DISPLAY}" ] && [ "$(tty)" = "/dev/tty1" ]; then
	# Cursor
	#export XCURSOR_THEME=Adwaita
	#export XCURSOR_SIZE=22
	
	# session and desktop
	export XDG_SESSION_TYPE=wayland
	export XDG_SESSION_DESKTOP=river
	export XDG_CURRENT_DESKTOP=river
	export DESKTOP_SESSION=river

	# for multi-gpu setup
	#export WLR_DRM_DEVICES=/dev/dri/card0

	# seat management
	# seatd is more minimal
	export LIBSEAT_BACKEND=seatd
	#export LIBSEAT_BACKEND=logind

	# QT
	export QT_QPA_PLATFORM=wayland-egl
	export QT_WAYLAND_DISABLE_WINDOWDECORATION=1

	# SDL
	export SDL_VIDEODRIVER=wayland

	# Clutter
	#export CLUTTER_BACKEND=wayland

	# Elementary/EFL
	#export ECORE_EVAS_ENGINE=wayland_egl
	#export ELM_ENGINE=wayland_egl
	#export ELM_DISPLAY=wl
	#export ELM_ACCEL=opengl

	# Mozilla
	export MOZ_ENABLE_WAYLAND=1
	# Open links in external applications in Firefox
	#export MOZ_DBUS_REMOTE=1

	# needed for some Java applications
	#export _JAVA_AWT_WM_NONREPARENTING=1
	
	export BROWSER=firefox
	#export BROWSER="${HOME}/.local/bin/ungoogled_chromium.sh"

	# set GTK theme
	export GTK_THEME=Adwaita:dark
	
	# finally start river
	exec river
fi
