#!/bin/bash

# print informations
phel() {
    cat << EOF
# wifi
iwdscan
iwctl station wlan0 show/scan/get-networks/(dis)connect

# bluez
blueon blueoff bluescan
bluetoothctl default-agent/power on/scan on/trust <device>/connect <device>

# audio
amixer/alsamixer (alsa)
pactl (pipewire)

# runit
ln -s /etc/sv/<service> /var/service/
ln -s /etc/sv/<service> /etc/runit/runsvdir/default/
touch /etc/sv/<service>/down
servstat (info services)

# removable drive
udisksctl (un)mount -b <drive (from lsblk)>

# decompression
aunpack (atool)
tar -x --<compression options> --strip-components=1 -C "<output dir>"

# update
xi -Su
update-extra all
build-packages update all
    
# git
git clone --recurse-submodules
git pull --recurse-submodules
git diff {--cached}
git rm {--cached} -r

# latex
lualatex {...}.tex

# pdf
pdfunite inputs.pdf output.pdf
EOF
    # TODO: expand print help
}
