#!/bin/bash

# print informations
phel() {
    cat << EOF
## wifi
iwscan
iwctl station wlan0 show/scan/get-networks/(dis)connect

## bluez
blueon blueoff bluescan
bluetoothctl default-agent/power on/scan on/trust <device>/connect <device>
when connecting mouse: riverctl-set-input mouse

## audio
amixer/alsamixer (alsa)
pactl (pipewire)
ffmpeg -i {file.ext} {file.ogg}
youtube-dl --ignore-errors --retries=infinite
    {--recode-video=ogg, --extract-audio --audio-format=opus}
    {{--embed-thumbnail} --add-metadata --xattrs}
    "<url>" -o "<name>.%(ext)s"
ydlv
ydla
ydlvm
ydlam

## runit
ln -s /etc/sv/<service> /var/service/
ln -s /etc/sv/<service> /etc/runit/runsvdir/default/
touch /etc/sv/<service>/down
servstat (info services)

## drives and devices
mount (list mounted drives and devices)
dd if=/dev/{zero,urandom} of=/dev/sda bs=4M status=progress
cat <...>.iso | pv > /dev/sda
udisksctl {un}mount -b <drive (from lsblk)>
findmnt

## (de)compression
aunpack (atool)
tar -x -<compression options (-z)> {--strip-components=1} -C "<output dir>"
tar -c -<compression options (-z)> -f "<archived.tar.gz>" "<to-archive>"

## update
xi -Su
update-extra all
build-packages all

## git
git clone --recurse-submodules
git pull --recurse-submodules
git diff {--cached}
git rm {--cached} -r
git remote show origin
git config --get remote.origin.url

## permission
stat
view the existing permissions of a file or directory in numeric form
stat -c %a "<name>"
default dir: 755
default file: 644
executable user: 744
executable all: 755

## man
man {character} search
# searching
apropos whatis
# updating
mandb
makewhatis
tldr

## latex
lualatex <...>.tex

## pdf
pdfunite inputs.pdf output.pdf

## terminal
terminfo
stty

## lib
ldconfig -v
ldconfig -n "$XDG_LIB_HOME"

## kernel
vkpurge list
vkpurge rm <kernel>

## font
fc-list
fc-cache -f -v
ttx <font-name>.<ttf,otf>
ttx <font-name>.<ttx>

## log
dmesg
svlogd

## util
date cal
uname
df -h du -h
diff -u
ps -e
pidof
pgrep, pkill, pwait
ip
EOF
}
