#!/bin/sh

### start all program/services in the background

## starting services with runsvdir

# start foot server
# foot --server &

# start pipewire (before waybar otherwise PulseAudio module may not start)
# pipewire &
# pipewire-pulse &
# # pipewire-media-session &

# start waybar
# waybar &

# Turin coordinates
# wlsunset -l 45.1 -L 7.7 &
# Lausanne coordinates
# wlsunset -l 46.5 -L 6.6 &

# libinput-gestures
# libinput-gestures &

# wob
if [ -p "$WOB_PIPE" ] || [ -p "$WOB_PIPE_CENTER" ]; then
    killall wob
    rm -f "$WOB_PIPE"
    rm -f "$WOB_PIPE_CENTER"
fi
mkfifo "$WOB_PIPE"
mkfifo "$WOB_PIPE_CENTER"
tail -f "$WOB_PIPE" | wob --anchor "top" --anchor "right" &
tail -f "$WOB_PIPE_CENTER" | wob --anchor "center" --width 400 &
# tail -f "$WOB_PIPE_CENTER" | wob --anchor "center" --width 400 --height 400 &

# load brightness level
adjust_brightness.sh load
# echo "brightness level is: $(adjust_brightness.sh load)"

# scale everything (problems with partial scaling)
# wlr-randr --output eDP-1 --scale 1.25

# use the "logo" key as the primary modifier
mod="Mod4"

# alt key
alt="Mod1"

### Programs

# mod + key used
# Return Backspace Space Period Comma
# {Up,Right,Down,Left} [0-9] F7 F11
# {H,J,K,L} Q F P U
# S A I B M

# Mod+Control+Return footclient
riverctl map normal "$mod"+Control Return spawn "footclient"
# Mod+Control+Backspace footclient float
riverctl map normal "$mod"+Control Backspace spawn "footclient --app-id=float"
# Mod+Control+Equal footclient float fullscreen
# TODO: currently not working
# riverctl map normal "$mod"+Control Equal spawn "footclient riverctl-float-fullscreen"

# Mod+S screenshot selection with grim and slurp
riverctl map normal "$mod" S spawn 'screenshot selection; echo "100" > $WOB_PIPE_CENTER'
# Mod+Shift+S screenshot fullscreen with grim and slurp
riverctl map normal "$mod"+Shift S spawn 'screenshot fullscreen; echo "100" > $WOB_PIPE_CENTER'
# old screenshot with grim and slurp
# riverctl map normal "$mod" S spawn 'grim -g "$(slurp)" - | wl-copy-env'

# Mod+A kak-fzf
riverctl map normal "$mod" A spawn "footclient --app-id=float fzf-kak"
# Mod+Shift+A kak-fzf from root
riverctl map normal "$mod"+Shift A spawn "footclient --app-id=float fzf-kak --from-root"

# Mod+I iwctl
riverctl map normal "$mod" I spawn "footclient --app-id=float iwctl"

# Mod+B iwctl
riverctl map normal "$mod" B spawn "footclient --app-id=float bluetoothctl"

# Mod+M fuzzel
riverctl map normal "$mod" M spawn "fuzzel.sh"

# Mod+Control+F firefox
riverctl map normal "$mod"+Control F spawn "firefox"
# Mod+Control+Shift+F firefox incognito mode
riverctl map normal "$mod"+Control+Shift F spawn "firefox -private-window"
# Mod+Shift+F firefox soft profile
riverctl map normal "$mod"+Shift F spawn "firefox -P soft"

# Mod+Control+F chromium
riverctl map normal "$mod"+Control C spawn "chromium-wayland"
# Mod+Control+Shift C chromium incognito mode
riverctl map normal "$mod"+Control+Shift C spawn "chromium-wayland --incognito"

### Windows

# Mod+Q to close the focused view
riverctl map normal "$mod" Q close

# Mod+Shift+E to exit river
riverctl map normal "$mod"+Shift E exit

# Mod+J and Mod+K to focus the next/previous view in the layout stack
riverctl map normal "$mod" J focus-view next
riverctl map normal "$mod" K focus-view previous

# Mod+Shift+J and Mod+Shift+K to swap the focused view with the next/previous
# view in the layout stack
riverctl map normal "$mod"+Shift J swap next
riverctl map normal "$mod"+Shift K swap previous

# Mod+Period and Mod+Comma to focus the next/previous output
riverctl map normal "$mod" Period focus-output next
riverctl map normal "$mod" Comma focus-output previous

# Mod+Shift+{Period,Comma} to send the focused view to the next/previous output
riverctl map normal "$mod"+Shift Period send-to-output next
riverctl map normal "$mod"+Shift Comma send-to-output previous

# Mod+Backspace focus previous tags
riverctl map normal "$mod" Backspace focus-previous-tags

# Mod+Shift+Backspace tag focused view with previous tags
riverctl map normal "$mod"+Shift Backspace send-to-previous-tags

# Mod+Return to bump the focused view to the top of the layout stack
riverctl map normal "$mod" Return zoom

# Mod+H and Mod+L to decrease/increase the main ratio of rivertile(1)
riverctl map normal "$mod" H send-layout-cmd rivertile "main-ratio -0.025"
riverctl map normal "$mod" L send-layout-cmd rivertile "main-ratio +0.025"

# Mod+Shift+H and Mod+Shift+L to increment/decrement the main count of rivertile(1)
riverctl map normal "$mod"+Shift H send-layout-cmd rivertile "main-count +1"
riverctl map normal "$mod"+Shift L send-layout-cmd rivertile "main-count -1"

# Mod+Alt+{H,J,K,L} to move views big step
# TODO: when moving to top move below bar
move_pixel_big=200
riverctl map normal "$mod"+"$alt" H move left   "$move_pixel_big"
riverctl map normal "$mod"+"$alt" J move down   "$move_pixel_big"
riverctl map normal "$mod"+"$alt" K move up     "$move_pixel_big"
riverctl map normal "$mod"+"$alt" L move right  "$move_pixel_big"

# Mod+Alt+Shift+{H,J,K,L} to move views small step
move_pixel_small=20
riverctl map normal "$mod"+"$alt"+Shift H move left     "$move_pixel_small"
riverctl map normal "$mod"+"$alt"+Shift J move down     "$move_pixel_small"
riverctl map normal "$mod"+"$alt"+Shift K move up       "$move_pixel_small"
riverctl map normal "$mod"+"$alt"+Shift L move right    "$move_pixel_small"

# Mod+Alt+Control+{H,J,K,L} to snap views to screen edges
# when snapping to top move below bar
riverctl map normal "$mod"+"$alt"+Control H snap    left
riverctl map normal "$mod"+"$alt"+Control J snap    down
riverctl map normal "$mod"+"$alt"+Control K spawn   riverctl-snap-up-bar
riverctl map normal "$mod"+"$alt"+Control L snap    right

# Mod+Control+{H,J,K,L} to resize views big step
resize_pixel_big=100
riverctl map normal "$mod"+Control H resize horizontal  "-$resize_pixel_big"
riverctl map normal "$mod"+Control J resize vertical    "-$resize_pixel_big"
riverctl map normal "$mod"+Control K resize vertical    "$resize_pixel_big"
riverctl map normal "$mod"+Control L resize horizontal  "$resize_pixel_big"

# Mod+Control+Shift+{H,J,K,L} to resize views small step
resize_pixel_small=10
riverctl map normal "$mod"+Control+Shift H resize horizontal  "-$resize_pixel_small"
riverctl map normal "$mod"+Control+Shift J resize vertical    "-$resize_pixel_small"
riverctl map normal "$mod"+Control+Shift K resize vertical    "$resize_pixel_small"
riverctl map normal "$mod"+Control+Shift L resize horizontal  "$resize_pixel_small"

# Mod+Alt+Control+Shift+{J,K,H,L} to change layout orientation
riverctl map normal "$mod"+"$alt"+Control+Shift H send-layout-cmd rivertile "main-location left"
riverctl map normal "$mod"+"$alt"+Control+Shift J send-layout-cmd rivertile "main-location bottom"
riverctl map normal "$mod"+"$alt"+Control+Shift K send-layout-cmd rivertile "main-location top"
riverctl map normal "$mod"+"$alt"+Control+Shift L send-layout-cmd rivertile "main-location right"

# Mod+{Left,Down,Up,Right} change tags
riverctl map normal "$mod" Left     spawn "cycle-focused-tags previous 9"
riverctl map normal "$mod" Down     spawn "cycle-focused-tags previous 9; cycle-focused-tags previous 9"
riverctl map normal "$mod" Up       spawn "cycle-focused-tags next 9; cycle-focused-tags next 9"
riverctl map normal "$mod" Right    spawn "cycle-focused-tags next 9"

# Mod+Left Mouse Button to move views
riverctl map-pointer normal "$mod" BTN_LEFT move-view

# Mod+Right Mouse Button to resize views
riverctl map-pointer normal "$mod" BTN_RIGHT resize-view

for i in $(seq 1 9); do
    tags="$((1 << (i - 1)))"

    # Mod+[1-9] to focus tag [1-9]
    riverctl map normal "$mod" "$i" set-focused-tags "$tags"

    # Mod+Shift+[1-9] to tag focused view with tag [1-9]
    riverctl map normal "$mod"+Shift "$i" set-view-tags "$tags"

    # Mod+Control+[1-9] to toggle focus of tag [1-9]
    riverctl map normal "$mod"+Control "$i" toggle-focused-tags "$tags"

    # Mod+Control+Shift+[1-9] to toggle tag [1-9] of focused view
    riverctl map normal "$mod"+Control+Shift "$i" toggle-view-tags "$tags"
done

# Mod+0 to focus all tags
# Mod+Shift+0 to tag focused view with all tags
all_tags="$(((1 << 32) - 1))"
riverctl map normal "$mod" 0 set-focused-tags "$all_tags"
riverctl map normal "$mod"+Shift 0 set-view-tags "$all_tags"

# scratchpad
# https://github.com/ifreund/river/wiki/Scratchpad
scratch_tag="$((1 << 20 ))"

# toggle the scratchpad with Super+P
riverctl map normal "$mod" P toggle-focused-tags "$scratch_tag"

# send windows to the scratchpad with Super+Shift+P
riverctl map normal "$mod"+Shift P set-view-tags "$scratch_tag"

# set spawn tagmask to ensure new windows does not have the scratchpad tag unless explicitly set
all_but_scratch_tag="$(( ((1 << 32) - 1) ^ scratch_tag ))"
riverctl spawn-tagmask "$all_but_scratch_tag"

# Mod+Space to toggle float
riverctl map normal "$mod" Space toggle-float

# Mod+F to toggle fullscreen
riverctl map normal "$mod" F toggle-fullscreen

# Mod+U set window float fullscreen (stacking mode)
riverctl map normal "$mod" U spawn riverctl-float-fullscreen

# Declare a passthrough mode. This mode has only a single mapping to return to
# normal mode. This makes it useful for testing a nested wayland compositor
riverctl declare-mode passthrough

# Mod+F11 to enter passthrough mode
riverctl map normal "$mod" F11 enter-mode passthrough

# Mod+F11 to return to normal mode
riverctl map passthrough "$mod" F11 enter-mode normal

# various media key mapping
for mode in normal locked; do
    # eject the optical drive
    riverctl map "$mode" None XF86Eject spawn 'eject -T'

    # control audio volume with alsa
    # for some reason -M option is not working
    # riverctl map "$mode" None XF86AudioRaiseVolume spawn "amixer -M set Master 5%+ | sed -En 's/.*\[([0-9]+)%\].*/\1/p' | head -1 > $WOB_PIPE"
    # riverctl map "$mode" None XF86AudioLowerVolume spawn "amixer -M set Master 5%- | sed -En 's/.*\[([0-9]+)%\].*/\1/p' | head -1 > $WOB_PIPE"
    # riverctl map "$mode" None XF86AudioMute spawn "amixer -M set Master toggle | sed -En '/\[on\]/ s/.*\[([0-9]+)%\].*/\1/ p; /\[off\]/ s/.*/0/p' | head -1 > $WOB_PIPE"

    # control microphone volume with alsa
    # for some reason -M option is not working
    # riverctl map "$mode" Shift XF86AudioRaiseVolume spawn "amixer -M set Capture 1%+ | sed -En 's/.*\[([0-9]+)%\].*/\1/p' | head -1 > $WOB_PIPE"
    # riverctl map "$mode" Shift XF86AudioLowerVolume spawn "amixer -M set Capture 1%- | sed -En 's/.*\[([0-9]+)%\].*/\1/p' | head -1 > $WOB_PIPE"
    # riverctl map "$mode" Shift XF86AudioMute spawn "amixer -M set Capture toggle | sed -En '/\[on\]/ s/.*\[([0-9]+)%\].*/\1/ p; /\[off\]/ s/.*/0/p' | head -1 > $WOB_PIPE"

    # control audio volume with pipewire
    riverctl map "$mode" None XF86AudioRaiseVolume spawn "pactl set-sink-volume @DEFAULT_SINK@ +5%; print-volume-pactl audio > $WOB_PIPE"
    riverctl map "$mode" None XF86AudioLowerVolume spawn "pactl set-sink-volume @DEFAULT_SINK@ -5%; print-volume-pactl audio > $WOB_PIPE"
    riverctl map "$mode" None XF86AudioMute spawn "pactl set-sink-mute @DEFAULT_SINK@ toggle; print-volume-mute-status-pactl audio > $WOB_PIPE"

    # control microphone volume with pipewire
    riverctl map "$mode" Shift XF86AudioRaiseVolume spawn "pactl set-source-volume @DEFAULT_SOURCE@ +5%; print-volume-pactl microphone > $WOB_PIPE"
    riverctl map "$mode" Shift XF86AudioLowerVolume spawn "pactl set-source-volume @DEFAULT_SOURCE@ -5%; print-volume-pactl microphone > $WOB_PIPE"
    riverctl map "$mode" Shift XF86AudioMute spawn "pactl set-source-mute @DEFAULT_SOURCE@ toggle; print-volume-mute-status-pactl microphone > $WOB_PIPE"

    # control MPRIS aware media players with playerctl
    riverctl map "$mode" None XF86AudioMedia spawn 'playerctl play-pause'
    riverctl map "$mode" None XF86AudioPlay  spawn 'playerctl play-pause'
    riverctl map "$mode" None XF86AudioPrev  spawn 'playerctl previous'
    riverctl map "$mode" None XF86AudioNext  spawn 'playerctl next'

    # brightness
    riverctl map "$mode" None XF86MonBrightnessUp   spawn "adjust_brightness.sh up > $WOB_PIPE"
    riverctl map "$mode" None XF86MonBrightnessDown spawn "adjust_brightness.sh down > $WOB_PIPE"

    # map power off key to lock system
    # done with acpi
    # riverctl map normal None XF86PowerOff spawn ""
    # riverctl map "$mode" None XF86PowerOff spawn ""
done

# Mod+F7 poweroff
riverctl map normal "$mod" F7 spawn "doas poweroff"
# Mod+Shift+F7 reboot
riverctl map normal "$mod"+Shift F7 spawn "doas reboot"
# Mod+Control+F7 zzz
riverctl map normal "$mod"+Control F7 spawn "doas zzz"

# spawn new window in less important part
riverctl attach-mode bottom

## set colors

# background
riverctl background-color 0x1d2021
# foreground 4
riverctl border-color-focused 0xa89984
# background 2
riverctl border-color-unfocused 0x504945
# red normal
riverctl border-color-urgent 0xcc241d
# default
# riverctl border-color-focused 0x93a1a1
# riverctl border-color-unfocused 0x586e75

# set border width
riverctl border-width 3

# moving the cursor on another window change focus
riverctl focus-follows-cursor disabled
# riverctl focus-follows-cursor normal

# set repeat rate
riverctl set-repeat 60 300

# cursor theme
# remember to change also .config/shell/envrc
# remember to change also .config/gtk-{2, 3}.0/{config, settings.ini}
# remember to change also .icons/default/index.theme
riverctl xcursor-theme Adwaita 16
# riverctl xcursor-theme OpenZone_White 32
# riverctl xcursor-theme Human 32

# make certain views start floating
# set app-ids of views which should float
# <https://git.sr.ht/~leon_plickat/lswt>
riverctl float-filter-add app-id "float"
riverctl float-filter-add app-id "popup"
riverctl float-filter-add app-id "mpv"
riverctl float-filter-add app-id "imv"

# set app-ids and titles of views which should use client side decorations
# riverctl csd-filter-add app-id "gedit"

# set up touchpad with riverctl
riverctl-set-input touchpad

# run extra initializations
river-init-extra

# start browser and footclient
river-init-session &

# set and exec into the default layout generator, rivertile
# river will send the process group of the init executable SIGTERM on exit
riverctl default-layout rivertile

# start rivertile without padding
# exec rivertile -view-padding 0 -outer-padding 0 -main-ratio 0.6

# starting with runit
# TODO: /run is mounted noexec so can't use XDG_RUNTIME_DIR
svdir="/tmp/$(id -u)-sv-$WAYLAND_DISPLAY"

pgrep -f "^runsvdir $svdir" &&
    exec echo "runsvdir already running for wayland session"

# recursive, deref links, preserve mode, if target is a dir, overwrite instead of copying into it
cp -rLpT "$HOME/.local/sv" "$svdir"

exec runsvdir "$svdir" \
    'log: ...........................................................................................................................................................................................................................................................................................................................................................................................................'
