### kakrc

# to install and update plugins kak-plugins-update

# source config files
evaluate-commands %sh{
    filetype="filetype"
    plugins="plugins"
    scripts="scripts"

    filetype_files="
        octave.kak
    "
        # kak-crosshairs/crosshairs.kak
        # number-toggle.kak/rc/number-toggle.kak
    plugins_files="
        foot.kak/rc/foot.kak
        kak-ansi/rc/ansi.kak
        kakoune-vertical-selection/vertical-selection.kak
        ui.kak/rc/ui.kak
        kakoune-text-objects/text-objects.kak
        kakoune-palette/palette.kak
        kakoune-state-save/state-save.kak
        kakoune-shellcheck/shellcheck.kak
        tiny.kak/rc/tiny.kak
        auto-pairs.kak/rc/auto-pairs.kak
        surround.kak/rc/surround.kak
    "
    scripts_files="
        indentation.kak
        wayland.kak
        git-commit-overflow.kak
        number-toggle.kak
        settings.kak
        key-bindings.kak
        functionality.kak
        modeline.kak
        doas-write.kak
        languages.kak
    "

    source_files() {
        prefix="$1"
        files="$2"
        for file in $files; do
             printf "%s" "
                 try %{
                     source %{${kak_config:?}/$prefix/$file}
                 } catch %{
                     echo -debug %val{error}
                 }
             "
        done
    }

    source_files "$filetype" "$filetype_files"
    source_files "$plugins" "$plugins_files"
    source_files "$scripts" "$scripts_files"
}
