#!/bin/sh
#
# Fuzzy find a file in directory subtree with fzf and edit in $EDITOR
#
# REQUIREMENTS: fzf - fd
# OPTIONALS:

"${EDITOR:-kak}" -- "$(fd --type file --follow --hidden -E .git --color=always | fzf --ansi)"
